services:
  postgres:
    image: postgres:latest
    container_name: postgresDB
    ports:
      - 5432:5432
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: sire
      POSTGRES_PASSWORD: 32h3fd
      POSTGRES_DB: asms
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: Test@asms.com
      PGADMIN_DEFAULT_PASSWORD: 5tusk7mam$
    volumes:
      - ./pgadmin:/var/lib/pgadmin
  asms:
    container_name: ASMS
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    env_file:
      - ./.env.local
    depends_on:
      - postgres

