spring.application.name=ASMS

#JWT Token key
rsa.rsa-private-key= ${PRIVATE_KEY}
rsa.rsa-public-key= ${PUBLIC_KEY}

#Database
spring.datasource.url= ${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.generate-ddl=true

#JWT Configuration
jwt.access= ${ACCESS_MINUTES:15}
jwt.refresh= ${REFRESH_HOURS:1}