spring.application.name=ASMS

#JWT Token key
rsa.rsa-private-key= ${PRIVATE_KEY}
rsa.rsa-public-key= ${PUBLIC_KEY}

#Database
spring.datasource.url=jdbc:postgresql://localhost:5432/
spring.datasource.username=postgres
spring.datasource.password=123456
spring.jpa.hibernate.ddl-auto=update
spring.jpa.generate-ddl=true

jwt.access = ${ACCESS_MINUTES:15}
jwt.refresh = ${REFRESH_HOURS:1}